In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv(r"C:\Users\Asus\Documents\MMU\degree sem 7 intern\Reports\ROS-SCRIPTS\real\1realnormal30m.pcap_Flow.csv")

In [ ]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330 entries, 0 to 329
Data columns (total 84 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Flow ID            330 non-null    object
 1   Src IP             330 non-null    object
 2   Src Port           330 non-null    int64
 3   Dst IP             330 non-null    object
 4   Dst Port           330 non-null    int64
 5   Protocol           330 non-null    int64
 6   Timestamp          330 non-null    object
 7   Flow Duration      330 non-null    int64
 8   Tot Fwd Pkts       330 non-null    int64
 9   Tot Bwd Pkts       330 non-null    int64
 10  TotLen Fwd Pkts    330 non-null    float64
 11  TotLen Bwd Pkts    330 non-null    float64
 12  Fwd Pkt Len Max    330 non-null    float64
 13  Fwd Pkt Len Min    330 non-null    float64
 14  Fwd Pkt Len Mean   330 non-null    float64
 15  Fwd Pkt Len Std    330 non-null    float64
 16  Bwd Pkt Len Max    330 non-null    float64
 17  Bwd Pkt Len Min    330 non-null    float64
 18  Bwd Pkt Len Mean   330 non-null    float64
 19  Bwd Pkt Len Std    330 non-null    float64
 20  Flow Byts/s        327 non-null    float64
 21  Flow Pkts/s        330 non-null    float64
 22  Flow IAT Mean      330 non-null    float64
 23  Flow IAT Std       330 non-null    float64
 24  Flow IAT Max       330 non-null    float64
 25  Flow IAT Min       330 non-null    float64
 26  Fwd IAT Tot        330 non-null    float64
 27  Fwd IAT Mean       330 non-null    float64
 28  Fwd IAT Std        330 non-null    float64
 29  Fwd IAT Max        330 non-null    float64
 30  Fwd IAT Min        330 non-null    float64
 31  Bwd IAT Tot        330 non-null    float64
 32  Bwd IAT Mean       330 non-null    float64
 33  Bwd IAT Std        330 non-null    float64
 34  Bwd IAT Max        330 non-null    float64
 35  Bwd IAT Min        330 non-null    float64
 36  Fwd PSH Flags      330 non-null    int64
 37  Bwd PSH Flags      330 non-null    int64
 38  Fwd URG Flags      330 non-null    int64
 39  Bwd URG Flags      330 non-null    int64
 40  Fwd Header Len     330 non-null    int64
 41  Bwd Header Len     330 non-null    int64
 42  Fwd Pkts/s         330 non-null    float64
 43  Bwd Pkts/s         330 non-null    float64
 44  Pkt Len Min        330 non-null    float64
 45  Pkt Len Max        330 non-null    float64
 46  Pkt Len Mean       330 non-null    float64
 47  Pkt Len Std        330 non-null    float64
 48  Pkt Len Var        330 non-null    float64
 49  FIN Flag Cnt       330 non-null    int64
 50  SYN Flag Cnt       330 non-null    int64
 51  RST Flag Cnt       330 non-null    int64
 52  PSH Flag Cnt       330 non-null    int64
 53  ACK Flag Cnt       330 non-null    int64
 54  URG Flag Cnt       330 non-null    int64
 55  CWE Flag Count     330 non-null    int64
 56  ECE Flag Cnt       330 non-null    int64
 57  Down/Up Ratio      330 non-null    float64
 58  Pkt Size Avg       330 non-null    float64
 59  Fwd Seg Size Avg   330 non-null    float64
 60  Bwd Seg Size Avg   330 non-null    float64
 61  Fwd Byts/b Avg     330 non-null    int64
 62  Fwd Pkts/b Avg     330 non-null    int64
 63  Fwd Blk Rate Avg   330 non-null    int64
 64  Bwd Byts/b Avg     330 non-null    int64
 65  Bwd Pkts/b Avg     330 non-null    int64
 66  Bwd Blk Rate Avg   330 non-null    int64
 67  Subflow Fwd Pkts   330 non-null    int64
 68  Subflow Fwd Byts   330 non-null    int64
 69  Subflow Bwd Pkts   330 non-null    int64
 70  Subflow Bwd Byts   330 non-null    int64
 71  Init Fwd Win Byts  330 non-null    int64
 72  Init Bwd Win Byts  330 non-null    int64
 73  Fwd Act Data Pkts  330 non-null    int64
 74  Fwd Seg Size Min   330 non-null    int64
 75  Active Mean        330 non-null    float64
 76  Active Std         330 non-null    float64
 77  Active Max         330 non-null    float64
 78  Active Min         330 non-null    float64
 79  Idle Mean          330 non-null    float64
 80  Idle Std           330 non-null    float64
 81  Idle Max           330 non-null    float64
 82  Idle Min           330 non-null    float64
 83  Label              330 non-null    object
dtypes: float64(45), int64(34), object(5)
memory usage: 216.7+ KB

,Flow ID,Src IP,Src Port,Dst IP,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,192.168.0.142-91.189.91.49-59030-80-6,192.168.0.142,59030,91.189.91.49,80,6,04/08/2025 02:35:25 PM,575315,3,4,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No Label
1,192.168.0.141-192.168.0.142-41770-36755-6,192.168.0.142,36755,192.168.0.141,41770,6,04/08/2025 02:34:46 PM,119974605,1183,1184,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No Label
2,192.168.0.141-192.168.0.142-46071-34678-6,192.168.0.141,46071,192.168.0.142,34678,6,04/08/2025 02:34:46 PM,119993117,2989,2991,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No Label
3,192.168.0.141-192.168.0.142-46071-34676-6,192.168.0.141,46071,192.168.0.142,34676,6,04/08/2025 02:34:46 PM,119994733,3499,3184,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No Label
4,192.168.0.141-192.168.0.142-46071-34690-6,192.168.0.141,46071,192.168.0.142,34690,6,04/08/2025 02:34:46 PM,119993138,2986,2988,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No Label

In [ ]:
# Drop these if not useful for your ML model
columns_to_drop = ['Flow ID', 'Src Port', 'Dst Port', 'Timestamp']
df.drop(columns=columns_to_drop, inplace=True, errors='ignore')

In [ ]:
filtered_df = df[
    ((df['Src IP'] == '192.168.0.142') & (df['Dst IP'] == '192.168.0.141')) |
    ((df['Src IP'] == '192.168.0.141') & (df['Dst IP'] == '192.168.0.142'))
]

In [ ]:
filtered_df['Label'].value_counts()

Label
BENIGN    141
Name: count, dtype: int64

In [ ]:
filtered_df = filtered_df.copy()
filtered_df['Label'] = 'BENIGN'

In [ ]:
filtered_df['Label'].value_counts()

Label
BENIGN    141
Name: count, dtype: int64

In [ ]:
filtered_df.head()  # Shows the first 5 rows

,Src IP,Dst IP,Protocol,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
1,192.168.0.142,192.168.0.141,6,119974605,1183,1184,62764.0,52.0,156.0,52.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2,192.168.0.141,192.168.0.142,6,119993117,2989,2991,355470.0,102.0,816.0,102.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
3,192.168.0.141,192.168.0.142,6,119994733,3499,3184,469938.0,134.0,938.0,134.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
4,192.168.0.141,192.168.0.142,6,119993138,2986,2988,355470.0,102.0,816.0,102.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
5,192.168.0.141,192.168.0.142,6,119984391,1387,1364,2273938.0,1905.0,1913.0,449.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN

In [ ]:
filtered_df.replace([float('inf'), -float('inf')], pd.NA, inplace=True)
filtered_df.dropna(inplace=True)

In [ ]:
filtered_df.head()  # Shows the first 5 rows

,Src IP,Dst IP,Protocol,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
1,192.168.0.142,192.168.0.141,6,119974605,1183,1184,62764.0,52.0,156.0,52.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2,192.168.0.141,192.168.0.142,6,119993117,2989,2991,355470.0,102.0,816.0,102.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
3,192.168.0.141,192.168.0.142,6,119994733,3499,3184,469938.0,134.0,938.0,134.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
4,192.168.0.141,192.168.0.142,6,119993138,2986,2988,355470.0,102.0,816.0,102.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
5,192.168.0.141,192.168.0.142,6,119984391,1387,1364,2273938.0,1905.0,1913.0,449.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN

In [ ]:
filtered_df.tail()  # Shows the last 5 rows

,Src IP,Dst IP,Protocol,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
325,192.168.0.141,192.168.0.142,6,119965827,2803,2805,356286.0,102.0,1122.0,102.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
326,192.168.0.141,192.168.0.142,6,119965817,2802,2804,356286.0,102.0,1122.0,102.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
327,192.168.0.142,192.168.0.141,6,119999531,1149,1149,62244.0,0.0,208.0,52.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
328,192.168.0.141,192.168.0.142,6,119949121,1454,1388,2266821.0,1897.0,2896.0,356.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
329,192.168.0.141,192.168.0.142,6,119945169,1462,1414,2266829.0,1897.0,2896.0,356.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN

In [ ]:
filtered_df.to_csv('clean_1realnormal30m.csv', index=False)

In [ ]:
import os
os.listdir()

['.ipynb_checkpoints',
 '1realnormal.pcap',
 '1realnormal.pcapng',
 '1realnormal.pcap_Flow.csv',
 '1realnormal30m.pcap',
 '1realnormal30m.pcapng',
 '1realnormal30m.pcap_Flow.csv',
 'cleaned_1realnormal30m.csv',
 'clean_1realnormal30m.csv',
 'normal.ipynb']

In [ ]:
df = pd.read_csv(r'C:\Users\Asus\Documents\MMU\degree sem 7 intern\Reports\ROS-SCRIPTS\real\clean_1realnormal30m.csv')
df.head()

,Src IP,Dst IP,Protocol,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,192.168.0.142,192.168.0.141,6,119974605,1183,1184,62764.0,52.0,156.0,52.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
1,192.168.0.141,192.168.0.142,6,119993117,2989,2991,355470.0,102.0,816.0,102.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2,192.168.0.141,192.168.0.142,6,119994733,3499,3184,469938.0,134.0,938.0,134.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
3,192.168.0.141,192.168.0.142,6,119993138,2986,2988,355470.0,102.0,816.0,102.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
4,192.168.0.141,192.168.0.142,6,119984391,1387,1364,2273938.0,1905.0,1913.0,449.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN

In [1]:
filtered_df['Label'].replace('BENIGN', 0, inplace=True)
display(filtered_df.head())

NameError: name 'filtered_df' is not defined

In [4]:
import pandas as pd
df = pd.read_csv(r"/content/1realnormal30m.pcap_Flow.csv")

columns_to_drop = ['Flow ID', 'Src Port', 'Dst Port', 'Timestamp']
df.drop(columns=columns_to_drop, inplace=True, errors='ignore')

filtered_df = df[
    ((df['Src IP'] == '192.168.0.142') & (df['Dst IP'] == '192.168.0.141')) |
    ((df['Src IP'] == '192.168.0.141') & (df['Dst IP'] == '192.168.0.142'))
]

filtered_df = filtered_df.copy()
filtered_df['Label'] = 'BENIGN'

filtered_df.replace([float('inf'), -float('inf')], pd.NA, inplace=True)
filtered_df.dropna(inplace=True)

filtered_df['Label'].replace('BENIGN', 0, inplace=True)
display(filtered_df.head())

/tmp/ipython-input-3061270688.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  filtered_df['Label'].replace('BENIGN', 0, inplace=True)
/tmp/ipython-input-3061270688.py:18: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  filtered_df['Label'].replace('BENIGN', 0, inplace=True)

,Src IP,Dst IP,Protocol,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
1,192.168.0.142,192.168.0.141,6,119974605,1183,1184,62764,52,156,52,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,192.168.0.141,192.168.0.142,6,119993117,2989,2991,355470,102,816,102,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,192.168.0.141,192.168.0.142,6,119994733,3499,3184,469938,134,938,134,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,192.168.0.141,192.168.0.142,6,119993138,2986,2988,355470,102,816,102,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
5,192.168.0.141,192.168.0.142,6,119984391,1387,1364,2273938,1905,1913,449,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0